### PR TITLE
Calibration save/load, gui cosmetics

### PR DESCRIPTION
**Pull request by nbgsmk**
Hello Jan!
I was playing with calibration and related stuff and I humbly :) propose some improvements:
calibration.cpp/h
- try to remember active cal.file name for later display
- suggest descriptive filename in "save calibration" dialog; created hzToString function to assist here. (I usually like to save my calibrations such as "cable abc, 40M-700M 400points", to distinguish from another cable e.g. "cable_xyz .... same as before". It gets a bit overwhelming if not precisely tracking wich cal file is which.) Anyway, the suggested filename is easy to delete by user, if they don't like it.

vna.cpp
- highlight "calibration" widget in yellow if calibration is not valid or not existing (any better idea?)
- show name of active cal.file if mouse hovered over widget (Couldn't think of a better place. Ideas, please?)
- slightly better logging if any problems during reading of cal.file

preferences.cpp
- when opening dialog, highlight first item in treeWidget

I have a couple other suggestions, but I would discuss with you first. One is related to calibration (remembering active cal. between switching modes). Would you like to discuss here or should I open another issue?
And a few other suggestions, about "ref" and "ref out" widgets, and dis/connection of device and calibration/interpolation... This definitely belongs in another issue(s). If you agree?

PS Sorry for using trace_math branch, I was stuck in it over the weekend and you are very fast in adding commits on your side... :-)

Zoran

### CODE REVIEW

**Comment by jankae** [comment]
Hi Zoran,
thanks again for the contribution, let's discuss your further ideas for the calibration here and please open a new issue for any suggestions regarding the reference toolbar.
Just a bit of feedback before I merge this:
* When starting the application and no calibration is in use, the calibration widget background is not yellow (it only turns yellow once a calibration was active and is disabled afterwards)
* I would prefer the usage of Unit::ToString for converting frequencies to human readable form (no need to have redundant code for that). It should be able to do the same stuff your hzToString does.
* Displaying the filename in the tooltip is okay, at least I don't know any better place just yet.

Also some other improvement suggestions from my side:
* Remember if calibration has been edited and add a notice about that as well to the tooltip. Maybe also add a popup if the application is closed and the edited calibration has not been saved yet? Could be useful, I already lost a calibration or two because I forgot to save it
* Indicate status of the calibration with background color and/or tooltip as well. The possible states are:
  * Exact (calibration created from same start/stop/points as the current sweep)
  * Interpolated (different start/stop/points but calibration completely covers the current sweep)
  * Extrapolated (calibration does not cover the complete sweep

Let me know if you want to take on any of these. I will wait for your response and then attempt to merge this pull request into the master branch (trace_math is my main "construction site" at the moment but not stable yet).

Jan

**Comment by nbgsmk** [comment]
Jan!
Good suggestions! I will definitely attack some of these, depending of my understanding of your code. And I must say it is quite nice and tidy, which helps me a lot. Let me think about these for a while, and I will let you know. Thanks!
Zoran

**Comment by nbgsmk** [comment]
Hi! 
Just a word, sorrry for my delay, I was busy for a while. I am digging back in over the weekend. Cheers!

**Comment by jankae** [comment]
Sorry, didn't mean to close this, just wanted to merge and delete the trace_math branch

**Comment by nbgsmk** [comment]
Good morning!
Here is my attempt at some of your suggestions. 

- When starting the application and no calibration is in use...
- Displaying the filename in the tooltip...

Well, the simplest option would be to show the same hint as it is now "bla bla 100M - 600M 1000pt", where the "600M" would be also yellow, assuming this is the limit which was crossed. But I don't see that styling parts of the tooltip text is possible. Am I right? Also, this approach is not very obvious for the user, so I'm not quite happy about it. 

So in parallel, I was thinking to add a QToolButton image  or this little thing image  and in case if interpolation turns yellow or red, the user would already have an idea to click or hover there. 
Ideally, the widget, the checkbox and combobox would be in a class of itself so the vna.cpp would be cleaner. I would love this, but wow, I would have to experiment heavily for that! :) Don't forget I am still learning Qt...

So much for the graphical look. I will be happy to hear your suggestions on this.

Regarding the initial state and changing during operation, I am definitely missing something. When app starts, the widget is initially red, but after changing start or stop of the sweep, nothing happens. Saving or loading the cal file works ok, but I was aiming to make it change as the start, stop, span... in the sweep toolbar are changing. In **VNA::getCalStyleStr()** and **VNA::getCalToolTip()** you would see the logic
cal type is extrapolation -> yellow
no cal -> red
all other cases -> revert to 'original' look (for types: no change, interpolation, exact)
Again, I would try to make this in a separate class, but at first it has to work from here. Probably I didn't catch the right signals or something like that. Kindly asking for help here, and/or suggestion on what to look for.


- I would prefer the usage of Unit::ToString

At least I got this one right! :-)

By the way, a great THANKS for saving/restoring the state of the panels/tiles! This was an idea for a long time... Another thought on this: when you leave only one chart on the screen, how to add another one? The only way I find is to delete the last remaining chart, and then the tile widget allows you to split the screen again. But then you loose all the settings such as span and x-y axes for the deleted chart. Am I right?

Final thought: I was kind'a lost in my local repo after you deleted the tracemath branch, so I had play with it and (re)clone several times until able to keep/merge my own changes from before, and continue from there. This is not a complaint, for sure! :) On the contrary, I am just hoping my pull request is now showing up correctly on your side. Let me know!

Zoran

**Pull request merged**
