### PR TITLE
Conversion of Eagle 9.3.1 to KiCad-5.1.7-1 of VNA2 (USB-C has been modified to HRO_TYPE-C-31-M-12)

### PR DESCRIPTION
**Pull request by bvernoux**
Full conversion with lot of manual fixes in schematic and board.

### CODE REVIEW

**Comment by bvernoux** [comment]
Example of VNA rendering with KiCad 5.1.7-1
image

**Comment by sp9bsl** [comment]
Hello Benjamin,
I see some ground problems around the input ports, take a look at the clearance to ground around GCPW. Compare it to the picture that Jan posted on the main page. Imported to Altium looks ok.

**Comment by bvernoux** [comment]
> Hello Benjamin,
> I see some ground problems around the input ports, take a look at the clearance to ground around GCPW. Compare it to the picture that Jan posted on the main page. Imported to Altium looks ok.

I do not have seen any issue anyway we can modify the clearance if required

**Comment by jankae** [comment]
Hi Benjamin,
thank you for all the work, I'll take a more detailed look later this week. For the impedance of the RF traces to be correct, the ground plane around them has to be pulled back a little. I used the tRestrict layer in Eagle to achieve that, it probably got lost during the import.

**Comment by bvernoux** [comment]
For information I consider that KiCad version to be v0.1 as there is lot of things to do like:
- Check Impedance, 
- Potentially switch to 6 Layers (it could be great to switch to 6 layers to have better ground/power layers...)
- Add the BOM in the schematic with part number for JLCPCB SMT...
- Improve some components/routing... to improve for frequencies >3GHz (and up to 6GHz)
...

**Comment by jankae** [comment]
I've had a chance to look a bit closer at the files and overall they look great! I noticed a couple of small issues:
* As mentioned before the additional ground clearance for RF traces is missing
* Are the holes for the screws present? I couldn't find them but maybe I am missing something.
* The ground plane cutouts under 0402 pads of resistors/capacitors in the RF path got imported wrong. Actually, this is more of an Eagle issue, because it does not support cutouts in internal layers. I had to use this [ugly solution](https://www.element14.com/community/thread/13637/l/making-cut-out-in-filled-polygon). KiCad then (correctly) filled the extra polygons, creating copper islands where a cutout should be. This is easily fixed by replacing them with proper cutouts.

Not really an issue with the current files but I am worried about future development: You mentioned a workflow to extract the soldermask from the step files. While this is certainly useful, the actual workflow I use is the other way around: I lay out the board with all its sections and screw positions first and then create the step files for the case (by exporting the soldermask to DXF and constructing the step files from that). I think it would be almost impossible to create the step files first (I don't know the position and size of the RF sections until I finish the layout) and quite tedious to manually create a matching step file for an existing board.

From what I've seen, KiCad has svg export for layers which would work just as well, but are round traces possible? I have not been able to find them yet. For PCB traces 45° corners are probably fine even for RF, but using round soldermask for the sections really helped to keep the board size small (and sharp inside corners can't be milled).

**Comment by kasbah** [comment]
> are round traces possible?

Not sure if it will work in this case but with a plugin they are: https://github.com/easyw/RF-tools-KiCAD/

**Comment by bvernoux** [comment]
> 
> 
> I've had a chance to look a bit closer at the files and overall they look great! I noticed a couple of small issues:
> 
>     * As mentioned before the additional ground clearance for RF traces is missing
> 
>     * Are the holes for the screws present? I couldn't find them but maybe I am missing something.
> 
>     * The ground plane cutouts under 0402 pads of resistors/capacitors in the RF path got imported wrong. Actually, this is more of an Eagle issue, because it does not support cutouts in internal layers. I had to use this [ugly solution](https://www.element14.com/community/thread/13637/l/making-cut-out-in-filled-polygon). KiCad then (correctly) filled the extra polygons, creating copper islands where a cutout should be. This is easily fixed by replacing them with proper cutouts.

The best is probably to modify the 0402 pads footprint for that or to create a new one for RF like RF_0402...

> 
> 
> Not really an issue with the current files but I am worried about future development: You mentioned a workflow to extract the soldermask from the step files. While this is certainly useful, the actual workflow I use is the other way around: I lay out the board with all its sections and screw positions first and then create the step files for the case (by exporting the soldermask to DXF and constructing the step files from that). I think it would be almost impossible to create the step files first (I don't know the position and size of the RF sections until I finish the layout) and quite tedious to manually create a matching step file for an existing board.

Yes the workflow shall be in reverse to extract PCB layers to create the shield, you can also do that with FreeCad 0.19 + https://github.com/easyw/kicadStepUpMod plugin

> 
> From what I've seen, KiCad has svg export for layers which would work just as well, but are round traces possible? I have not been able to find them yet. For PCB traces 45° corners are probably fine even for RF, but using round soldermask for the sections really helped to keep the board size small (and sharp inside corners can't be milled).

For RF (round tracks, solder mask expansion, teardrops trace, via stitching, advanced footprint for RF)
I recommend the following amazing plugins (which all works perfectly with KiCad 5.1.7-1):
- https://github.com/easyw/RF-tools-KiCAD
- https://github.com/easyw/kicad-action-scripts
- https://github.com/easyw/kicad-action-tools

Also a must have to do manual assembly:
- https://github.com/openscopeproject/InteractiveHtmlBom

**Comment by jankae** [comment]
> The best is probably to modify the 0402 pads footprint for that or to create a new one for RF like RF_0402...

I don't think that's possible, the cutout is on the internal ground layer. I wasn't able to add internal layer features to footprints. But this is not really a problem, the cutouts can easily be placed manually.

> I recommend the following amazing plugins

For round RF traces it is okay I guess. It is somewhat more work than the rounded traces I am used to in Eagle. But than again you don't really need that many round traces. However, none of the plugins work on the soldermask (as you can't put traces on the mask layer). You can of course draw arcs on the mask layer and I thought this would be the solution when I also found the "Convert to polygon" function in kicad-nightly (my idea was to draw the outline of the soldermask and than convert it into a polygon to fill it. This is pretty close to my workflow in Eagle). But again, the conversion to polygon seems to be only possible with traces (on copper layers).
Is there no way to draw polygons with round features on the mask layers?

I wanted to add the mounting holes for the screws and noticed that the holes in the soldermask layers are not aligned with the grid (all holes are on a 0.5mm grid in the original files). In fact the complete mask features imported from the step files seem to be scaled slightly too big (they extend beyond the board edges). I believe that has to be fixed before tackling the other issues but is probably beyond my (non-existent) kicad-skills. Could you help out, @bvernoux?

**Comment by bvernoux** [comment]
I have not worked more on the KiCad board but a nice upgrade will be to change the SMA to use https://www.digikey.com/en/products/detail/amphenol-rf/901-10510-2/6051059 which are not too expensive (for the quality and native matching) and with very good specifications (up to 26.5GHz which seems overkill) and does not requires specific matching (like for other cheap SMA connectors).
To clearly define the cut out under the different traces it will be definitely requires so simulation my aim for that project will be to improve it to reach 8GHz or more (without changing too much actual PCB).

**Pull request merged**
