### PR TITLE
SignalGen - more precision digits; ui panel mod.

### PR DESCRIPTION
**Pull request by nbgsmk**
Hi Jan!
I propose more digits in the frequency widget of signal gen.
And a slight modificaiton of ui panel. Just moved title "generator" to the top of the panel.

I am thinking also of changing the frequency input widget to double spin box. Maybe even to show both lineedit and double spin box, so users can change in both of them as they like. What do you think?
Zoran

### CODE REVIEW

**Comment by jankae** [comment]
More digits are probably justified here ;) I am actually thinking of adding a functionality to siunitedits in general, where you can change their value with the scroll wheel (sort of like the spinbox). This could be useful in a lot of places (e.g. when setting up a port extension) and that could also be used here. One thing I am not sure of yet is how to determine the increment per scroll wheel movement.

**Comment by nbgsmk** [comment]
My thoughts exactly! It would be great even in more places, like axis setup, start, stop, span, etc.
But a fixed step would become too small at higher values, and a percentage-based spin may lead to non-round numbers (unless handled).
Combining this with siunitedit, where completely different units are in play, looks a bit overwhelming. Remains open for thinking...

**Comment by jankae** [comment]
I had something like changing the nth digit with the scroll wheel in mind. For example, if the value is in [1.0, 10.0), the increment could be 0.1. And in the range [10, 100) it would be 1. There is still the special case of a value of zero and the decision which digit is used for the increment (smaller resolution vs. fast changes to other orders of magnitudes).

**Comment by jankae** [comment]
I have implemented that idea, the scroll wheel always changes the 3rd digit: 3a88e10
This seems quite usable, thanks for the idea :)

**Pull request merged**
